# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os: linux
dist: focal
language: r
warnings_are_errors: true
cache: packages
r: bioc-release
bioc_check: true

jobs:
  include:
    - stage: prepare cache
      script:
        - echo cache warm-up, do not run R CMD check
      after_success:
        - echo cache warm-up, do not run coveralls
    - stage: test

apt_packages:
  - gsl-bin
  - libgsl0-dev

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::coveralls()'
