# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os: linux
dist: focal
language: r
warnings_are_errors: true
cache: packages
r: bioc-release
r_build_args: "--no-build-vignettes --no-manual"
r_check_args: "--no-build-vignettes --no-vignettes --ignore-vignettes --no-manual --as-cran --no-tests --no-examples"
bioc_check: true

jobs:
  include:
    - stage: prepare cache
      script:
        - echo No R CMD check since this is a cache warmup
      after_success:
        - echo No codecov / biocheck since this is a cache warmup
    - stage: test

apt_packages:
  - gsl-bin
  - libgsl0-dev

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::coveralls()'
