# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
r: bioc-release

before_install:
  - sudo apt-get update
  - sudo apt-get -y install gsl-bin libgsl0-dev

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::coveralls()'
